### ISSUE TITLE
[Feature Request] Breakdown of individual items durability status on Mouseover

### ISSUE THREAD

**Issue by boktai1000** [Xruptor/xanDurability#5]
Hey there! Thanks for the great addon, being able to quickly visualize this in the middle of say a raid gone poorly to know what your expenses are is definitely great, I'm a fan of just having more information at my fingertips.

But one additional thing I'm looking for is knowing the cost of individual pieces, and what exactly is broken/breaking and needs repairs.

I'm thinking an option to give, on mouseover, a breakdown of items both equipped and in your bag a line item of if they have incurred durability loss, their current durability status as well as gold to repair them. Definitely don't need to show items at 100% - just the ones currently weighing against you that you have.

Thanks for the great addon!

**Comment by Xruptor** [comment]
Sorry for the delay, I've had so many things come up lately. 

In terms of your request, that does sound like a pretty good idea.  I'll look into the code and see what I can do.

**Comment by Xruptor** [comment]
Added it :)
