### ISSUE TITLE
Error in version 11.0

### ISSUE THREAD

**Issue by fozi** [Xruptor/xanDurability#8]
The addon still appears to work but this error is generated upon the loading.

4x XanDurability/config.lua:137: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@XanDurability/config.lua"]:137: in function <XanDurability/config.lua:92>
[string "@XanDurability/config.lua"]:144: in function `EnableConfig'
[string "@XanDurability/xanDurability.lua"]:96: in function `EnableAddon'
[string "@XanDurability/xanDurability.lua"]:46: in function <XanDurability/xanDurability.lua:35>

Locals:
about = XanDurabilityAboutPanel {
 name = "XanDurability"
}
fields = <table> {
 1 = "Version"
 2 = "Author"
}
notes = "A small window that displays the total current armour durability."
title = FontString {
}
subtitle = FontString {
}
anchor = FontString {
}
(*temporary) = nil
(*temporary) = XanDurabilityAboutPanel {
 name = "XanDurability"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
ADDON_NAME = "XanDurability"

**Comment by Xruptor** [comment]
Apparently the recent patch as well as the changes found in next expansion TWW,  is causing a lot of bugs.  I'll tackle these one at a time.

This bug seems very similar to one I had with BagSync.  I'll need to compare.
