### ISSUE TITLE
Error in 11.0.2

### ISSUE THREAD

**Issue by jgleigh** [Xruptor/xanDurability#9]
63x XanDurability/xanDurability.lua:279: attempt to call field 'SurfaceArgs' (a nil value)
[string "@XanDurability/xanDurability.lua"]:279: in function `GetDurabilityInfo'
[string "@XanDurability/xanDurability.lua"]:466: in function <XanDurability/xanDurability.lua:465>
[string "=(tail call)"]: ?

Locals:
self = XanDurability {
 IsRetail = true
 IsClassic = false
 IsWLK_C = false
 backdropInfo = <table> {
 }
 aboutPanel = XanDurabilityAboutPanel {
 }
 Center = Texture {
 }
 RightEdge = Texture {
 }
 BottomEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
 BottomLeftCorner = Texture {
 }
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 addSpace = false
 configFrame = XanDurability_config_eventFrame {
 }
 TopEdge = Texture {
 }
 moreDurInfo = <table> {
 }
 settingsCategory = <table> {
 }
 LeftEdge = Texture {
 }
}
(for state) = <table> {
 IndexHandType = 10
 IndexFingerType = 11
 IndexThrownType = 25
 IndexTabardType = 19
 IndexHoldableType = 23
 IndexProfessionGearType = 30
 IndexBodyType = 4
 IndexHeadType = 1
 IndexRobeType = 20
 IndexNonEquipType = 0
 IndexWaistType = 6
 IndexTrinketType = 12
 IndexEquipablespellUtilityType = 32
 IndexRelicType = 28
 IndexRangedrightType = 26
 IndexFeetType = 8
 IndexShieldType = 14
 IndexAmmoType = 24
 IndexWeaponoffhandType = 22
 IndexWristType = 9
 IndexProfessionToolType = 29
 IndexEquipablespellDefensiveType = 33
 Index2HweaponType = 17
 IndexNeckType = 2
 IndexEquipablespellWeaponType = 34
 IndexBagType = 18
 IndexRangedType = 15
 IndexLegsType = 7
 IndexShoulderType = 3
 IndexChestType = 5
 IndexQuiverType = 27
 IndexEquipablespellOffensiveType = 31
 IndexWeaponType = 13
 IndexWeaponmainhandType = 21
 IndexCloakType = 16
}
(for control) = "IndexHandType"
slotName = "IndexHandType"
slotID = 10
hasItem = <table> {
 dataInstanceID = 816
 type = 0
 isAzeriteItem = false
 guid = "Item-155-0-400000099FE6210A"
 id = 217182
 isAzeriteEmpoweredItem = false
 isCorruptedItem = false
 lines = <table> {
 }
}
repairCost = nil
(*temporary) = nil
(*temporary) = <table> {
 dataInstanceID = 816
 type = 0
 isAzeriteItem = false
 guid = "Item-155-0-400000099FE6210A"
 id = 217182
 isAzeriteEmpoweredItem = false
 isCorruptedItem = false
 lines = <table> {
 }
}
(*temporary) = "attempt to call field 'SurfaceArgs' (a nil value)"
pEquipDura = <table> {
 min = 0
 max = 0
}
pBagDura = <table> {
 min = 0
 max = 0
}
equipCost = 0
bagCost = 0
totalCost = 0

**Comment by Xruptor** [comment]
Please let me know if this version fixes it.

[xanDurability.zip](https://github.com/user-attachments/files/16613233/xanDurability.zip)

**Comment by jgleigh** [comment]
Yes that fixes it. Thanks.
